[DATABASE]
host = 47.92.229.35
username = root
password = 123456
port = 3306
database = modouyudb

[HTTP]
#接口的URL
base_url = http://127.0.0.1
port = 8889
timeout = 1.0

[EMAIL]
mail_host = smtp.163.com
mail_user = qiuhanqiu@163.com
mail_pass = qiu0604
mail_port = 25
sender = qiuhanqiu@163.com
receiver = qiuhanqiu@163.com,814779251@qq.com
subject = python
content = "All interface test has been complited.Please read the report file about the detile of result in the attachment."
testuser = qiu
on_off = on